title:              Blog
email:              christodoulossantorinaios@gmail.com
description:        Let's talk data
author:             Christodoulos Santorinaios
baseurl:            ""
url:                "https://csantor.github.io/blog"

# Social Profiles
twitter_username:   
github_username:    csantor
facebook_username:  
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           
paginate:           3
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
